import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Provider from "./Provider";
import AppBar from "./AppBar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  console.log(params, "params");

  return (
    <html lang="en">
      <body className={poppins.className}>
        <div>
          <Provider>
            {/* <AppBar /> */}
            <AntdRegistry>{children}</AntdRegistry>
          </Provider>
        </div>
      </body>
    </html>
  );
}
